/*////////////////////////////////////////////////////
Yes, this set is part of my revenge agaist Jerem Vol.2
Fat Mouse
////////////////////////////////////////////////////*/

/*////////////////////////////////////////////////////
SET GLOBALCONFIG
////////////////////////////////////////////////////*/
layout('fr');
hide=true;
typingSpeed(50,100)

/*////////////////////////////////////////////////////
Script
////////////////////////////////////////////////////*/
press("GUI");
delay(500);
type("Paramètres de la Souris")
delay(500);
press("ENTER");
delay(500);
press("DOWN");
delay(300);
press("TAB");
delay(200);
press("TAB");
delay(200);
typingSpeed(0,0)
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
typingSpeed(50,100)
delay(300);
press("TAB");
delay(200);
press("TAB");
delay(200);
press("ENTER");
delay(300);
typingSpeed(0,0)
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
press("RIGHT");
delay(200);
typingSpeed(50,100)
press("TAB");
delay(200);
press("RIGHT");
press("RIGHT");
press("RIGHT");
delay(300);
press("ENTER");
delay(500);
press("TAB");
delay(200);
press("RIGHT");
delay(200);
press("RIGHT");
delay(200);
press("RIGHT");
delay(300);
press("ENTER");
press("ALT F4");
step = Math.PI / 90.0;
scale = 6.0
alpha = 0.0
horizontal = false;
while(true) {
	v = Math.cos(alpha) * scale;
	alpha += step;
	if (horizontal) moveStepped(v,0);
	else moveStepped(0,v);
	delay(10);
}
